wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.1
bsz:
  desc: null
  value: 16
channel_factor:
  desc: null
  value: 64
checkpoint_path:
  desc: null
  value: /home/jumperkables/kable_management/projects/Visual-modelling/cnn_visual_modelling/.results/2poc_5-1_multi_500g_2d-d3_sl1_mean/model.pth
dataset:
  desc: null
  value: hudsons
dataset_path:
  desc: null
  value: data/hudsons_multi_ygrav/500/6_dset.pickle
depth:
  desc: null
  value: 3
device:
  desc: null
  value: cuda:0
early_stopping:
  desc: null
  value: 3
epoch:
  desc: null
  value: 300
extract_dset:
  desc: null
  value: false
gif_path:
  desc: null
  value: /home/jumperkables/cnn_visual_modelling/.results/self_out.gif
img_type:
  desc: null
  value: greyscale
in_no:
  desc: null
  value: 5
jobname:
  desc: null
  value: 2poc_5-1_multi_500g_2d-d3_sl1_mean
krnl_size:
  desc: null
  value: 3
krnl_size_t:
  desc: null
  value: 3
loss:
  desc: null
  value: smooth_l1
model:
  desc: null
  value: UpDown2D
model_path:
  desc: null
  value: /home/jumperkables/cnn_visual_modelling/model.pth
n_gifs:
  desc: null
  value: 20
out_no:
  desc: null
  value: 1
padding:
  desc: null
  value: 1
padding_t:
  desc: null
  value: 1
plotter:
  desc: null
  value: <tools.visdom_plotter.VisdomLinePlotter object at 0x7fe597a5b820>
reduce:
  desc: null
  value: true
reduction:
  desc: null
  value: mean
results_dir:
  desc: null
  value: /home/jumperkables/kable_management/projects/Visual-modelling/cnn_visual_modelling/.results/2poc_5-1_multi_500g_2d-d3_sl1_mean
save:
  desc: null
  value: true
self_output:
  desc: null
  value: true
self_output_n:
  desc: null
  value: 100
shuffle:
  desc: null
  value: true
train_ratio:
  desc: null
  value: 0.8
val_bsz:
  desc: null
  value: 100
visdom:
  desc: null
  value: true
